/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6p2_carlosmurillo;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;

/**
 *
 * @author Jafeth
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    DefaultListModel modelopersonas =  new DefaultListModel();
    DefaultListModel modelonjetos =  new DefaultListModel();
    DefaultComboBoxModel modelo_c_personas = new DefaultComboBoxModel();
    
    private ArrayList lista_perosnas = new ArrayList();
    public Principal() {
        initComponents();
        p_gerente.setVisible(true);
        p_personas.setVisible(false);
        
        p_zapatos.setVisible(true);
        p_ropa.setVisible(false);
        p_hogar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo = new javax.swing.ButtonGroup();
        estado = new javax.swing.ButtonGroup();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        p_c_personas = new javax.swing.JPanel();
        p_personas = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        t_ocupacion = new javax.swing.JTextField();
        t_horario = new javax.swing.JTextField();
        t_tiempo = new javax.swing.JTextField();
        t_sueldo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Datos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        combo_tipo = new javax.swing.JComboBox<>();
        t_id = new javax.swing.JTextField();
        t_nombre = new javax.swing.JTextField();
        t_edad = new javax.swing.JTextField();
        b_masculino = new javax.swing.JRadioButton();
        b_femenino = new javax.swing.JRadioButton();
        b_soltero = new javax.swing.JRadioButton();
        b_casado = new javax.swing.JRadioButton();
        t_altura = new javax.swing.JTextField();
        t_peso = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        p_gerente = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        t_usuario = new javax.swing.JTextField();
        t_contra = new javax.swing.JTextField();
        combo_cargo = new javax.swing.JComboBox<>();
        crear_p = new javax.swing.JButton();
        p_c_objetos = new javax.swing.JPanel();
        Datos_o = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        combo_personas = new javax.swing.JComboBox<>();
        combo_t_o = new javax.swing.JComboBox<>();
        b_color = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_descripcion = new javax.swing.JTextArea();
        t_marca = new javax.swing.JTextField();
        t_tamano = new javax.swing.JTextField();
        t_calidad = new javax.swing.JTextField();
        p_zapatos = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        t_suela = new javax.swing.JScrollPane();
        t_de_suela = new javax.swing.JTextArea();
        t_talla = new javax.swing.JTextField();
        t_comodidad = new javax.swing.JTextField();
        p_ropa = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        t_pais = new javax.swing.JTextField();
        t_tela = new javax.swing.JTextField();
        t_talla_r = new javax.swing.JTextField();
        p_hogar = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        t_garantia = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        descripcion_h = new javax.swing.JScrollPane();
        t_descripcion_h = new javax.swing.JTextArea();
        t_instrucciones = new javax.swing.JScrollPane();
        t_instrucciones_h = new javax.swing.JTextArea();
        crear_o = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lista_p = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lista_o = new javax.swing.JList<>();
        jLabel48 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p_c_personas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Personas Generales");

        jLabel17.setText("Ocupacion");

        jLabel18.setText("Horario");

        jLabel19.setText("Tiempo trabajando");

        jLabel20.setText("Sueldo");

        jLabel21.setText("semanas");

        jLabel22.setText("lps");

        javax.swing.GroupLayout p_personasLayout = new javax.swing.GroupLayout(p_personas);
        p_personas.setLayout(p_personasLayout);
        p_personasLayout.setHorizontalGroup(
            p_personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_personasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_personasLayout.createSequentialGroup()
                        .addGroup(p_personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(p_personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_personasLayout.createSequentialGroup()
                                .addComponent(t_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22))
                            .addComponent(t_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_horario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(p_personasLayout.createSequentialGroup()
                                .addComponent(t_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21))))
                    .addComponent(jLabel13))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        p_personasLayout.setVerticalGroup(
            p_personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_personasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(p_personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(t_ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(t_horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(t_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(22, 22, 22)
                .addGroup(p_personasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(t_sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        p_c_personas.add(p_personas, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 19, -1, -1));

        jLabel1.setText("Ingrese los Datos del Tipo de Persona");

        jLabel2.setText("Tipo de Persona");

        jLabel3.setText("ID");

        jLabel4.setText("Nombre");

        jLabel5.setText("Edad");

        jLabel6.setText("Sexo");

        jLabel7.setText("Estado civil");

        jLabel8.setText("Altura");

        jLabel9.setText("Peso");

        combo_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente", "Personal General" }));
        combo_tipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo_tipoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                combo_tipoMouseExited(evt);
            }
        });
        combo_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tipoActionPerformed(evt);
            }
        });

        sexo.add(b_masculino);
        b_masculino.setText("M");

        sexo.add(b_femenino);
        b_femenino.setText("F");

        estado.add(b_soltero);
        b_soltero.setText("Soltero");

        estado.add(b_casado);
        b_casado.setText("Casado");

        jLabel10.setText("cms");

        jLabel11.setText("lbs");

        javax.swing.GroupLayout DatosLayout = new javax.swing.GroupLayout(Datos);
        Datos.setLayout(DatosLayout);
        DatosLayout.setHorizontalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(DatosLayout.createSequentialGroup()
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(31, 31, 31)
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DatosLayout.createSequentialGroup()
                                .addComponent(t_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(DatosLayout.createSequentialGroup()
                                .addComponent(t_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addGroup(DatosLayout.createSequentialGroup()
                                .addComponent(b_soltero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_casado))
                            .addGroup(DatosLayout.createSequentialGroup()
                                .addComponent(b_masculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_femenino))
                            .addComponent(t_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DatosLayout.setVerticalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(combo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(b_masculino)
                    .addComponent(b_femenino))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(b_soltero)
                    .addComponent(b_casado))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(t_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(t_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(0, 75, Short.MAX_VALUE))
        );

        p_c_personas.add(Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel44.setText("Gerente");

        jLabel45.setText("Usuario");

        jLabel46.setText("Contraseña");

        jLabel47.setText("Cargo");

        combo_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente de Plata", "Gerente de Sucursal" }));
        combo_cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_cargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_gerenteLayout = new javax.swing.GroupLayout(p_gerente);
        p_gerente.setLayout(p_gerenteLayout);
        p_gerenteLayout.setHorizontalGroup(
            p_gerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_gerenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_gerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_gerenteLayout.createSequentialGroup()
                        .addGroup(p_gerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(jLabel46)
                            .addComponent(jLabel45))
                        .addGap(18, 18, 18)
                        .addGroup(p_gerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_usuario)
                            .addComponent(t_contra)
                            .addComponent(combo_cargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel44))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        p_gerenteLayout.setVerticalGroup(
            p_gerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_gerenteLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel44)
                .addGap(18, 18, 18)
                .addGroup(p_gerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(t_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_gerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel46)
                    .addComponent(t_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_gerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(combo_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        p_c_personas.add(p_gerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 19, -1, -1));

        crear_p.setText("Crear");
        crear_p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crear_pMouseClicked(evt);
            }
        });
        p_c_personas.add(crear_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 90, -1));

        jTabbedPane7.addTab("Crear Persona", p_c_personas);

        p_c_objetos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setText("Ingrese los Datos del Tipo de Objeto");

        jLabel24.setText("Tipo de objeto");

        jLabel25.setText("Color");

        jLabel26.setText("Descripcion");

        jLabel27.setText("Marca");

        jLabel28.setText("Tamaño");

        jLabel29.setText("Calidad");

        jLabel30.setText("Persona que lo ingreso");

        combo_t_o.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zapatos", "Ropa", "Hogar" }));
        combo_t_o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_t_oActionPerformed(evt);
            }
        });

        b_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_colorMouseClicked(evt);
            }
        });

        t_descripcion.setColumns(20);
        t_descripcion.setRows(5);
        jScrollPane1.setViewportView(t_descripcion);

        javax.swing.GroupLayout Datos_oLayout = new javax.swing.GroupLayout(Datos_o);
        Datos_o.setLayout(Datos_oLayout);
        Datos_oLayout.setHorizontalGroup(
            Datos_oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Datos_oLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Datos_oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(Datos_oLayout.createSequentialGroup()
                        .addGroup(Datos_oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(Datos_oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Datos_oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(t_calidad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(t_tamano, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(t_marca, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(combo_personas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combo_t_o, javax.swing.GroupLayout.Alignment.LEADING, 0, 110, Short.MAX_VALUE)
                                .addComponent(b_color, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Datos_oLayout.setVerticalGroup(
            Datos_oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Datos_oLayout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(Datos_oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(combo_t_o, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Datos_oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(b_color, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Datos_oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Datos_oLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(82, 82, 82)
                        .addGroup(Datos_oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(t_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Datos_oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(t_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Datos_oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(t_calidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(Datos_oLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(combo_personas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 103, Short.MAX_VALUE))
        );

        p_c_objetos.add(Datos_o, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel31.setText("Zapatos");

        jLabel32.setText("Talla");

        jLabel33.setText("Descripcion suela");

        jLabel34.setText("Comodidad");

        t_de_suela.setColumns(20);
        t_de_suela.setRows(5);
        t_suela.setViewportView(t_de_suela);

        javax.swing.GroupLayout p_zapatosLayout = new javax.swing.GroupLayout(p_zapatos);
        p_zapatos.setLayout(p_zapatosLayout);
        p_zapatosLayout.setHorizontalGroup(
            p_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_zapatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addGroup(p_zapatosLayout.createSequentialGroup()
                        .addGroup(p_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(p_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_comodidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_talla, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_suela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        p_zapatosLayout.setVerticalGroup(
            p_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_zapatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addGroup(p_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(t_talla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addGroup(p_zapatosLayout.createSequentialGroup()
                        .addComponent(t_suela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(p_zapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_comodidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        p_c_objetos.add(p_zapatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 34, 350, 310));

        jLabel35.setText("Ropa");

        jLabel36.setText("Talla");

        jLabel37.setText("Tipo de tela");

        jLabel38.setText("Pais de elab.");

        javax.swing.GroupLayout p_ropaLayout = new javax.swing.GroupLayout(p_ropa);
        p_ropa.setLayout(p_ropaLayout);
        p_ropaLayout.setHorizontalGroup(
            p_ropaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_ropaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_ropaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addGroup(p_ropaLayout.createSequentialGroup()
                        .addGroup(p_ropaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(jLabel37)
                            .addComponent(jLabel36))
                        .addGap(18, 18, 18)
                        .addGroup(p_ropaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_pais)
                            .addComponent(t_tela)
                            .addComponent(t_talla_r, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        p_ropaLayout.setVerticalGroup(
            p_ropaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_ropaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addGroup(p_ropaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(t_talla_r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_ropaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(t_tela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p_ropaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(t_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        p_c_objetos.add(p_ropa, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 34, 350, 310));

        jLabel39.setText("Hogar");

        jLabel40.setText("Descripcion");

        jLabel41.setText("Tiempo de garantia");

        jLabel42.setText("Instrucciones");

        jLabel43.setText("meses");

        t_descripcion_h.setColumns(20);
        t_descripcion_h.setRows(5);
        descripcion_h.setViewportView(t_descripcion_h);

        t_instrucciones_h.setColumns(20);
        t_instrucciones_h.setRows(5);
        t_instrucciones.setViewportView(t_instrucciones_h);

        javax.swing.GroupLayout p_hogarLayout = new javax.swing.GroupLayout(p_hogar);
        p_hogar.setLayout(p_hogarLayout);
        p_hogarLayout.setHorizontalGroup(
            p_hogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hogarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_hogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_hogarLayout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_instrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_hogarLayout.createSequentialGroup()
                        .addGroup(p_hogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addGroup(p_hogarLayout.createSequentialGroup()
                                .addGroup(p_hogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel41))
                                .addGap(18, 18, 18)
                                .addGroup(p_hogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descripcion_h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(p_hogarLayout.createSequentialGroup()
                                        .addComponent(t_garantia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel43)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_hogarLayout.setVerticalGroup(
            p_hogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_hogarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addGap(18, 18, 18)
                .addGroup(p_hogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcion_h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40))
                .addGap(18, 18, 18)
                .addGroup(p_hogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_hogarLayout.createSequentialGroup()
                        .addComponent(t_instrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(p_hogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_garantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43)
                            .addComponent(jLabel41)))
                    .addComponent(jLabel42))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        p_c_objetos.add(p_hogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 34, 350, 310));

        crear_o.setText("Crear");
        crear_o.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crear_oMouseClicked(evt);
            }
        });
        p_c_objetos.add(crear_o, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 70, -1));

        jTabbedPane7.addTab("Crear Objeto", p_c_objetos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1238, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jTabbedPane7.addTab("Modificar Persona", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1238, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jTabbedPane7.addTab("Modificar Objeto", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1238, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jTabbedPane7.addTab("Jerarquia de Personas", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1238, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jTabbedPane7.addTab("Jerarquia de Objetos", jPanel6);

        jScrollPane5.setViewportView(lista_p);

        jLabel12.setText("Nombre");

        jLabel14.setText("Rol");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel14)))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(327, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("Lista de Personas", jPanel7);

        jLabel15.setText("Color");

        jLabel16.setText("Marca");

        jScrollPane6.setViewportView(lista_o);

        jLabel48.setText("Persona que lo ingreso");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel16)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel48)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("Lista de Objetos", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane7)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane7)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_tipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_tipoMouseClicked

    }//GEN-LAST:event_combo_tipoMouseClicked

    private void combo_tipoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_tipoMouseExited

    }//GEN-LAST:event_combo_tipoMouseExited

    private void combo_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tipoActionPerformed
        int num = combo_tipo.getSelectedIndex();
        String cadena = combo_tipo.getItemAt(num);
        if(cadena.equals("Gerente")){
            p_gerente.setVisible(true);
            p_personas.setVisible(false);
        }else if(cadena.equals("Personal General")){
            p_personas.setVisible(true);
            p_gerente.setVisible(false);
        }
        else{
            p_gerente.setVisible(false);
            p_personas.setVisible(false);
        }
    }//GEN-LAST:event_combo_tipoActionPerformed

    private void combo_t_oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_t_oActionPerformed
        int num = combo_t_o.getSelectedIndex();
        String cadena = combo_t_o.getItemAt(num);
        if(cadena.equals("Zapatos")){
            p_zapatos.setVisible(true);
            p_ropa.setVisible(false);
            p_hogar.setVisible(false);
        }else if(cadena.equals("Ropa")){
            p_zapatos.setVisible(false);
            p_ropa.setVisible(true);
            p_hogar.setVisible(false);
        }else if(cadena.equals("Hogar")){
            p_zapatos.setVisible(false);
            p_ropa.setVisible(false);
            p_hogar.setVisible(true);
        }
        else{
            p_zapatos.setVisible(false);
            p_ropa.setVisible(false);
            p_hogar.setVisible(false);
        }
    }//GEN-LAST:event_combo_t_oActionPerformed

    private void combo_cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_cargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_cargoActionPerformed

    private void crear_pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crear_pMouseClicked
        int num = combo_tipo.getSelectedIndex();
        
        
        String tipo = combo_tipo.getItemAt(num);
        String id = t_id.getText();
        String nombre = t_nombre.getText();
        int edad = Integer.parseInt(t_edad.getText());
        String sexo = "";
        if(b_masculino.isSelected()){
            sexo = "Masculino";
        }else{
            sexo = "Femenino";
        }
        String estado = "";
        if(b_soltero.isSelected()){
            estado = "Soltero";
        }else{
            estado = "Casado";
        }
        double altura = Integer.parseInt(t_altura.getText());
        double peso = Integer.parseInt(t_peso.getText());
        if(tipo.equals("Gerente")){
            String usuario = t_usuario.getText();
            String contra = t_contra.getText();
            int numc = combo_cargo.getSelectedIndex();
            String cargo = combo_cargo.getItemAt(numc);
            lista_perosnas.add(nombre);
            modelopersonas.addElement(new Personas(tipo, id, nombre, edad, sexo, estado, altura, peso, usuario, contra, cargo));
        }else{
            String ocupacion = t_ocupacion.getText();
            String horario = t_horario.getText();
            int tiempo = Integer.parseInt(t_tiempo.getText());
            double sueldo = Integer.parseInt(t_sueldo.getText());
            lista_perosnas.add(nombre);
            modelopersonas.addElement(new Personas(tipo, id, nombre, edad, sexo, estado, altura, peso, ocupacion, horario, tiempo, sueldo));
        }
        modelo_c_personas.addElement(nombre);
        lista_p.setModel(modelopersonas);
        combo_personas.setModel(modelo_c_personas);
        
        t_id.setText("");
        t_nombre.setText("");
        t_edad.setText("");
        t_id.setText("");
        t_altura.setText("");
        t_peso.setText("");
        t_ocupacion.setText("");
        t_horario.setText("");
        t_tiempo.setText("");
        t_sueldo.setText("");
        t_usuario.setText("");
        t_contra.setText("");
    }//GEN-LAST:event_crear_pMouseClicked

    private void crear_oMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crear_oMouseClicked
        int num = combo_t_o.getSelectedIndex();
        String tipo = combo_t_o.getItemAt(num);
        Color color = b_color.getBackground();
        String descripcion = t_descripcion.getText();
        String marac = t_marca.getText();
        int tamano = Integer.parseInt(t_tamano.getText());
        String calidad = t_calidad.getText();
        int num2 = combo_personas.getSelectedIndex();
        String persona = (String) lista_perosnas.get(num2);
        
        if(tipo.equals("Zapatos")){
            String talla = t_talla.getText();
            String suela = t_de_suela.getText();
            String comodidad = t_comodidad.getText();
            modelonjetos.addElement(new Objetos(tipo, color, descripcion, marac, talla, calidad, persona, talla, suela, comodidad));
        }else if(tipo.equals("Ropa")){
            String talla = t_talla_r.getText();
            String tela = t_tela.getText();
            String pais = t_pais.getText();
            modelonjetos.addElement(new Objetos(tipo, color, descripcion, marac, tela, calidad, persona, talla, tela, pais, num));
        }else if(tipo.equals("Hogar")){
            String descripcion1 = t_descripcion_h.getText();
            String instrucciones = t_instrucciones_h.getText();
            int tiempo = Integer.parseInt(t_garantia.getText());
            modelonjetos.addElement(new Objetos(tipo, color, descripcion, marac, marac, calidad, persona, descripcion1, instrucciones, tiempo));
        }else{
            
        }

        lista_o.setModel(modelonjetos);
        
        
        
    }//GEN-LAST:event_crear_oMouseClicked

    private void b_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_colorMouseClicked
        b_color.setBackground(JColorChooser.showDialog(this, "Seleccione un color", Color.yellow)
        );
    }//GEN-LAST:event_b_colorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windoes".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Datos;
    private javax.swing.JPanel Datos_o;
    private javax.swing.JRadioButton b_casado;
    private javax.swing.JButton b_color;
    private javax.swing.JRadioButton b_femenino;
    private javax.swing.JRadioButton b_masculino;
    private javax.swing.JRadioButton b_soltero;
    private javax.swing.JComboBox<String> combo_cargo;
    private javax.swing.JComboBox<String> combo_personas;
    private javax.swing.JComboBox<String> combo_t_o;
    private javax.swing.JComboBox<String> combo_tipo;
    private javax.swing.JButton crear_o;
    private javax.swing.JButton crear_p;
    private javax.swing.JScrollPane descripcion_h;
    private javax.swing.ButtonGroup estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JList<String> lista_o;
    private javax.swing.JList<String> lista_p;
    private javax.swing.JPanel p_c_objetos;
    private javax.swing.JPanel p_c_personas;
    private javax.swing.JPanel p_gerente;
    private javax.swing.JPanel p_hogar;
    private javax.swing.JPanel p_personas;
    private javax.swing.JPanel p_ropa;
    private javax.swing.JPanel p_zapatos;
    private javax.swing.ButtonGroup sexo;
    private javax.swing.JTextField t_altura;
    private javax.swing.JTextField t_calidad;
    private javax.swing.JTextField t_comodidad;
    private javax.swing.JTextField t_contra;
    private javax.swing.JTextArea t_de_suela;
    private javax.swing.JTextArea t_descripcion;
    private javax.swing.JTextArea t_descripcion_h;
    private javax.swing.JTextField t_edad;
    private javax.swing.JTextField t_garantia;
    private javax.swing.JTextField t_horario;
    private javax.swing.JTextField t_id;
    private javax.swing.JScrollPane t_instrucciones;
    private javax.swing.JTextArea t_instrucciones_h;
    private javax.swing.JTextField t_marca;
    private javax.swing.JTextField t_nombre;
    private javax.swing.JTextField t_ocupacion;
    private javax.swing.JTextField t_pais;
    private javax.swing.JTextField t_peso;
    private javax.swing.JScrollPane t_suela;
    private javax.swing.JTextField t_sueldo;
    private javax.swing.JTextField t_talla;
    private javax.swing.JTextField t_talla_r;
    private javax.swing.JTextField t_tamano;
    private javax.swing.JTextField t_tela;
    private javax.swing.JTextField t_tiempo;
    private javax.swing.JTextField t_usuario;
    // End of variables declaration//GEN-END:variables
}
